### ISSUE TITLE
[MISSING] Code of Conduct, Issue Template

### ISSUE THREAD

**Issue by FahimFBA** [bluzeey/Downqueue#1]
Your project is missing the Code of Conduct & the Issue Template. Let me know if you want me to add a PR with all of those.

**Comment by bluzeey** [comment]
Yeah , go ahead , but I do have made a Readme for overview of the project.
I have not made code of conduct and other so , yeah , please make them

**Comment by FahimFBA** [comment]
I can also make the README prettier if you want later. For now, let me finish the other things. I need an email address that would get enlisted in the Code of Conduct.

**Comment by bluzeey** [comment]
Add this one
